/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vint32_t ;
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#define RCC_BASE   0x40010800
#define GPIO_CRH    *(volatile uint32_t *)(GPIO_BASE +0x04)
#define GPIO_ODR    *(volatile uint32_t *)(GPIO_BASE +0x0C)
int main(void)
{
    /* Loop forever */
	for(;;);
}
